### PR TITLE
(#648) Tweaks to avoid OTA halting when using TLS.

### PR DESCRIPTION
**Pull request by nemidiy**
+ During OTA do not publish any messages that are not OTA related
+ Publish 1 every 100 206 status messages

### CODE REVIEW

**Comment by nemidiy** [comment]
cpplint failed. I did a commit --amend but looks like someone with write privileges need to rerun that part of the pipeline.

**Comment by codefrey** [comment]
@nemidiy The  force-pushed commit still contains the errors the linter is complaining about.

IMHO it would be better to rate limit the OTA calls to `_publishOtaStatus` in `__handleOTAUpdates` instead of just dismissing them.

**Comment by nemidiy** [comment]
@codefrey yes, it was just the guy behind the keyboard messing up. You bring a valid point, I moved the code so that if anyone wants to come a up with a more sophisticated approach they don't have to move it. thanks!

**Comment by kleini** [comment]
Will test the latest changes on my devices.

**Pull request merged**
