### PR TITLE
Ported to esp32 / Adapt library to Homie 3.0.0

### PR DESCRIPTION
**Pull request by tantive**
-Ported to esp32. homie-esp8266 now supports architectures esp32 and esp8266.
-Successfully tested with M5Stick/Environment Sensor (https://docs.m5stack.com/#/en/core/m5stick, https://docs.m5stack.com/#/en/unit/env) on openHAB 2.4 / mosquitto 1.4.15.
-For increased openhab2.4 compatibility $stats/interval is now set correctly and published on every stats update (see https://github.com/eclipse/smarthome/issues/6495).
-On esp32 OTA and LED support are currently not working (future work needs to be done, see #FIXME comments).

### CODE REVIEW

**Comment by stritti** [comment]
Maybe for OTA-support following project could help? -> https://github.com/craftmetrics/esp32-homie

**Comment by stritti** [comment]
I think there is missing update of `docs` to have third param at `HomieNode`s:

```
- HomieNode temperatureNode("temperature", "temperature");
+ HomieNode temperatureNode("temperature", "Temperature", "temperature");
```

e.g. quickstart/getting-started/

**Comment by stritti** [comment]
> I think there is missing update of `docs` to have third param at `HomieNode`s:
> 
> ```
> - HomieNode temperatureNode("temperature", "temperature");
> + HomieNode temperatureNode("temperature", "Temperature", "temperature");
> ```
> e.g. quickstart/getting-started/

✔ Great, it is updated. Thank you very much!

**Comment by euphi** [comment]
PR was for wrong branch, so I created a new one and merged it. (5b34a624950f533bf85b42efad1158bed7823caf)
Many Thanks!

**Pull request closed without merging**
