### PR TITLE
Optimize JSON code

### PR DESCRIPTION
**Pull request by codefrey**
* Simplify JSON lookups
* Remove unnecessary lookups
* Add null checks for JSON strings before calling strlen()

### CODE REVIEW

**Comment by codefrey** [comment]
While writing this patch I noticed that `Validation.cpp` enforces the `["ota"]["enabled"]` object to exist, whilst `Config.cpp` would assume OTA to be disabled if it was not part of the configuration.

Should I change this behaviour to make the OTA setting completely optional?

**Comment by bertmelis** [comment]
> Should I change this behaviour to make the OTA setting completely optional?

Reading the docs, `ota enabled` is not optional. https://homieiot.github.io/homie-esp8266/docs/develop-v3/configuration/json-configuration-file/

But imho it should be and the docs should be changed. The docs should be changed anyways because of the confusion it now generates for OTA updates and OTA configuration updates.

**Comment by MajorTwip** [comment]
Is  #605 included in this PR?

**Comment by codefrey** [comment]
@MajorTwip I haven't forgotten you. :)
I wrote a recursive way of patching the config, which will allow to create / replace any element in the configuration. But this is not part of this PR since I was not sure if everyone would be happy with it and I didn't want it to be a blocker for this code.

**Comment by MajorTwip** [comment]
Great, thx

**Comment by codefrey** [comment]
@MajorTwip I opened a pull request for the patching (#628). Feel free to take a look at it and to test it.

**Pull request merged**
