### PR TITLE
Fix OTA problems for ESP32

### LINKED ISSUE #575: Esp32, OTA, MD5 checksum
As you all probably know already, the Esp32-OTA implementation is not working properly.
There's a problem with the getSketchMD5 esp32 function which ends in a boot loop. This function works properly in other sketchs and if we move the MD5 calculation from where it is (begining of bootnormal.cpp) in the bootnormal::setup procedure, it works without any problems.

### PR DESCRIPTION
**Pull request by bodiroga**
Hi guys!

Thanks to the great instructions provided by @jeanvdr and @bertmelis, OTA updates are now working for ESP32 boards. I don't have any ESP8266 with me right now, so please test it on those boards before merging!

Closes #575

Signed-off-by: Aitor Iturrioz <riturrioz@gmail.com>

### CODE REVIEW

**Comment by tantive** [comment]
@bodiroga Tested OTA on a M5Stick (ESP32), works like a charm. Thank you!
Should be save to merge this PR.

**Comment by bodiroga** [comment]
@stritti, how many approves do we need to merge a PR?

**Comment by bertmelis** [comment]
> @stritti, how many approves do we need to merge a PR?

for a confirmed bugfix I'd hope only one.

**Comment by stritti** [comment]
@bodiroga I hope also one approval should be enough. I am very new in the project and hoped that e.g. @euphi will merge.

**Comment by stritti** [comment]
I merged now.

**Pull request merged**
