### PR TITLE
Towards V2.1

### PR DESCRIPTION
**Pull request by timpur**
- [x] Add ability to remove settings via incremental updates ( #420 )
- [x] Fix incremental update trying to add setting items when previously no settings object exists in the config.
- [x] Add the ability to access settings before setup ( #372 )
- [x] Add the ability to set the values of settings in homie and save to the config file ( #457 )
- [x] Get Device ID (#463)
- [x] TLS support + fingerprint attribute in config file ( #399 )
- [ ] Update Config UI for new features in the config file ( Also make it Smaller #469 ) (https://github.com/marvinroger/homie-esp8266-setup/issues/3) ( #446 )
- [x] MQTT Restart Device
- [ ] Fix MQTT retained messages ( #313 )
- [ ] Fix Bugs (#478 #320)
- [ ] Add incremental config updates via config mode (Web UI and API) ( #433 )
- [ ] Add possibly Upload Firmware via config mode (Web UI and API).
- [ ] Size of firmware ( #471 )
- [ ] Refactor Arduino Json to use latest lib to make config code more efficient. (https://arduinojson.org/api/jsonvariant/or/)
- [ ] Documentation 
- [ ] Update Examples
- [ ] Improve interface with '/set' prop

### CODE REVIEW

**Comment by timpur** [comment]
@marvinroger @ThomDietrich @tripflex @euphi @bertmelis 

Will be changing from debounc2 to [One Button](https://github.com/mathertel/OneButton) this this will be more beneficial to homie and homie's user base. This will allow us to add a feature of changing boot modes via double click to swap over to config mode with out reset to update config via the ui or api.

It will also mean that users using buttons in there project will not need to look else where to get click, double click and long press functionality. This will also open up a handler for users to hook on to for normal button clicks (the rest used for homie) on the Homie reset button (GPIO 0)

Would like to know if there any major issues with this change, but its something i will go forward with for v2.1. I think this lib will serve us better. I know it will be breaking, but it is v2.1 so .....

**Comment by kylegordon** [comment]
With regards to the One Button change, have you seen https://github.com/pkourany/clickButton at all? I currently use it with good effect for up to 3 clicks and 3 clicks and hold. From what I've seen, One Button only supports single and double click.

I can't vouch for the code at all, other than "it works" - https://github.com/kylegordon/homie-sonoff-touch

**Comment by ThomDietrich** [comment]
Both are healthy since ~2014. The One Button seems to be more famous (Stars count) but clickButton offers more functionality. Did you compare code overhead?

**Comment by timpur** [comment]
Defs will look into, thanks guys.

**Comment by timpur** [comment]
@tripflex, about to add some new changes + some changes to the ui config site. This will allow homie to use the ui to update the the config and no need for resetting the device. Also some the ui can now support all config settings like manual ip, ssl ect. When i do release these changes can you also test them with me ?

**Comment by kylegordon** [comment]
@timpur sorry, I missed your message a month ago :-(

The way I interpret it is that a 'double long press' (-2) is tap once, then tap and hold. triple being two taps followed by a hold.

I'll double check shortly and let you know if it's different

**Comment by timpur** [comment]
Yeah for me when testing that's how I got to -2 and -3, thought that was a bit odd and not what I was looking for ....

**Comment by timpur** [comment]
@tripflex use the new ui to test out patch updates to the config 
https://github.com/timpur/homie-esp8266-setup/blob/revamp/ui_bundle.gz

**Comment by luebbe** [comment]
Concerning the short and long presses: I implemented something similar a while ago. The short presses select the function and the long press confirms it. If you don't confirm within a second, the state switches back to "nothing".
Example: 
* 2x short + 1x long -> activate function two
* 3x short + 1x long -> activate function three
* 3x short -> nothing happens
* 1x long -> nothing happens (unless you implement a function zero)

So there's no Morse "short short long long short" possible :)

**Comment by timpur** [comment]
My issue is how do I get 3x long 
It doesn't seem to work with that lib clickButton

**Comment by luebbe** [comment]
I understand your problem. But is it really a problem in terms of usability? Isn't it easier to remember: "Reset config -> function 3 -> 3x short 1x long to confirm" instead of "Reset config = long long long", "Function xyz = long short long"?

**Comment by euphi** [comment]
@timpur Do you know, why this PR was never merged? I try to get an overview of the changes, but these are too many to understand them soon :scream: . However, it seems at least some of them are useful also for #develop-v3 branch.

**Comment by timpur** [comment]
@euphi think i was to ambitious with the task list :P

Maybe best to port some of the changes to the new branch ... ?

**Comment by euphi** [comment]
Interestingly, therre is no merge conflict, although there were some many other commits on the #develop branch.

**Comment by euphi** [comment]
@timpur Can you help with selecting the important commits? (Or help with testing. especially the changes to config mode, because I don't use the config mode).

**Comment by timpur** [comment]
I will try help out when I can :)

Though I welcome others to also Chery pick commits into smaller PRs. I should of done this ...

**Comment by stritti** [comment]
I close this PR. Most features are implemented on #develop-v3 now.

**Pull request closed without merging**
