### PR TITLE
Fix SonoffDualShutters example

### LINKED ISSUE #569: Cannot compile example provided - "shutters"
Arduino 1.8.5 on Windows.
All libraries used in sketch updated to latest version ( 21/feb/2019)

The example used -  "SonoffDualShutters.ino"

Here is an output:
```
SonoffDualShutters:60: error: no matching function for call to 'Shutters::Shutters(const long unsigned int&, void (&)(), void (&)(), void (&)(), uint8_t (&)(), void (&)(uint8_t), const float&, void (&)(uint8_t))'

Shutters shutters(COURSE_TIME, shuttersUp, shuttersDown, shuttersHalt, shuttersGetState, shuttersSetState, CALIBRATION_RATIO, onShuttersLevelReached);

                                                                                                                                                     ^

C:\Users\<my-user-name>\Documents\Arduino\libraries\homie-esp8266\examples\SonoffDualShutters\SonoffDualShutters.ino:60:149: note: candidates are:

In file included from C:\Users\<my-user-name>\Documents\Arduino\libraries\homie-esp8266\examples\SonoffDualShutters\SonoffDualShutters.ino:22:0:

C:\Users\<my-user-name>\Documents\Arduino\libraries\arduino-shutters\src/Shutters.h:75:3: note: Shutters::Shutters()

   Shutters();

   ^

C:\Users\<my-user-name>\Documents\Arduino\libraries\arduino-shutters\src/Shutters.h:75:3: note:   candidate expects 0 arguments, 8 provided

C:\Users\<my-user-name>\Documents\Arduino\libraries\arduino-shutters\src/Shutters.h:39:7: note: constexpr Shutters::Shutters(const Shutters&)

 class Shutters {

       ^

C:\Users\<my-user-name>\Documents\Arduino\libraries\arduino-shutters\src/Shutters.h:39:7: note:   candidate expects 1 argument, 8 provided

C:\Users\<my-user-name>\Documents\Arduino\libraries\arduino-shutters\src/Shutters.h:39:7: note: constexpr Shutters::Shutters(Shutters&&)

C:\Users\<my-user-name>\Documents\Arduino\libraries\arduino-shutters\src/Shutters.h:39:7: note:   candidate expects 1 argument, 8 provided
```

Using library homie-esp8266 at version 2.0.0 in folder: C:\Users\<my-user-name>\Documents\Arduino\libraries\homie-esp8266

### PR DESCRIPTION
**Pull request by luebbe**
This fixes #569. It compiles on my PC. The fix is completely untested, because I don't have a Sonoff Dual

### CODE REVIEW

**Comment by luebbe** [comment]
Interesting. It compiles with vscode/platformio, but fails under circleci.

**Comment by kleini** [comment]
Will have a look. My SSH feature made some tests fail, too. In my case, this was too large images for too small devices due to all that additional code, that came with upgraded libraries.

**Comment by luebbe** [comment]
The CircleCi output looks like it uses a different version of the shutters library. I'll have a look at the CircleCI config. Missed that completely.

**Comment by luebbe** [comment]
Ok, basically I ported the shuttes example to the head version of the shutters library. I can either roll back and list the correct (old dependencies) in SonoffDualShutters.ino or change the dependencies in the circleci config. I'd prefer the latter, because others are going to fall into that trap too.

**Comment by luebbe** [comment]
Now it compiles on CircleCI, but I also get the program size error for the 1MB ESP

**Comment by kleini** [comment]
This is my commit, to replace 512K ESP01 with the 1MB version: https://github.com/homieiot/homie-esp8266/pull/577/commits/0472fb6380073c5ce91edd12b88d90ab60a767bd

**Comment by luebbe** [comment]
would you merge it to the develop branch then? It's  only on develop-v3.

**Comment by stritti** [comment]
@luebbe could you rebase to branch `develop` please?
Renaming the branches closed the PR. Sorry.

**Pull request closed without merging**
